spring:
  profiles:
    active: eureka7001
---
spring:
  profiles: eureka7001
server:
  port: 7001
eureka:
  instance:
    hostname: zc.eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
       defaultZone: http://zc.eureka7002.com:7002/eureka/,http://zc.eureka7003.com:7003/eureka/
---
spring:
  profiles: eureka7002
server:
  port: 7002
eureka:
  instance:
    hostname: zc.eureka7002.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://zc.eureka7001.com:7001/eureka/,http://zc.eureka7003.com:7003/eureka/
---
spring:
  profiles: eureka7003
server:
  port: 7003
eureka:
  instance:
    hostname: zc.eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://zc.eureka7002.com:7002/eureka/,http://zc.eureka7001.com:7001/eureka/


