#spring:
#  application:
#    name: application.yml
#zuul:
#  routes:
#    a.serviceId: dept-provider
#    a.path: /bbb/**
#  ignored-services: "*"
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-dev
server:
  port: 8596
---
spring:
  profiles: test
  application:
    name: spring-cloud-test
server:
  port: 8597